config/routes.rb
Rails.application.routes.draw do

  get 'logs/index'

  get 'logs/destroy'

  devise_for :users

  resources :lunchtables
  resources :lunches

  root 'lunchtables#index'
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/lunch.rb
class Lunch < ActiveRecord::Base
  belongs_to :user
  belongs_to :lunchtable
end

app/models/lunchtable.rb
class Lunchtable < ActiveRecord::Base
  has_many :lunches, dependent: :destroy
  has_many :users, through: :lunches


  def update_val
    total = price.to_i * users.length.to_i
    self.update(total: total)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :lunches
  has_many :lunchtables, through: :lunches

  def update_bal(cost, paid)
    new_balance = self.balance.to_f + paid.to_f - cost.to_f
    self.update(balance: new_balance)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

 protected

 def configure_devise_permitted_parameters
   registration_params = [:balance, :name, :email, :password, :password_confirmation]

   if params[:action] == 'update'
     devise_parameter_sanitizer.for(:account_update) {
       |u| u.permit(registration_params << :current_password)
     }
   elsif params[:action] == 'create'
     devise_parameter_sanitizer.for(:sign_up) {
       |u| u.permit(registration_params)
     }
   end
 end

end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
    @logs = Log.all
  end

  def destroy
    Log.destroy_all
    Log.create(info: "#{current_user.name} flushed all of the logs on #{Time.now}")
    redirect_to logs_index_path
  end
end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController

  def show
  end

  def edit
    session[:return_to] ||= request.referer
    @lunch = Lunch.find(params[:id])
  end

  def update
    @lunch = Lunch.find(params[:id])
    prev = @lunch.paid
    if @lunch.update(lunch_params)
      Log.create(info: "#{current_user.name} updated how much #{@lunch.user.name} paid from #{prev} to #{lunch_params[:paid]} on the #{l(@lunch.lunchtable.created_at,format: :short)} Table")
      redirect_to session.delete(:return_to)
    else
      render :edit
    end
  end

  def new
    @lunch = Lunch.new
  end

  def create
    @table = Lunchtable.find (params[:lunchtable_id])
    users = @table.users
    lunch = Lunch.new(user: current_user, lunchtable: @table, paid: 0)
    if users.where(id: current_user.id).empty?
      if lunch.save
          @table.update_val
          Log.create(info: "#{current_user.name} joined the #{l(@table.created_at,format: :short)} table.")
         redirect_to @table
      end
    else
      redirect_to @table
    end
  end

    def destroy
      @lunch = Lunch.find( params[:id] )
      @table = Lunchtable.find(@lunch.lunchtable_id)
      Log.create(info: "#{current_user.name} left the #{l(@table.created_at,format: :short)} table.")
      @lunch.destroy
      @table.update_val
      redirect_to @table
    end

  private

   def lunch_params
     params.require(:lunch).permit(:paid)
   end
end

app/controllers/lunchtables_controller.rb
class LunchtablesController < ApplicationController
  before_action :authenticate_user!
  def index
    @tables = Lunchtable.all
    render component: 'Tablelist', props: { tables: @tables }, tag: 'span', class: 'todo'
  end

  def new
    @lunchtable = Lunchtable.new
  end

  def create
    @lunchtable = Lunchtable.new(params[:id])
    x = lunchtable_params
    x[:total] = (lunchtable_params[:price].to_f * @lunchtable.users.length).to_f
    x[:price] = x[:price].to_i
    if @lunchtable.update(x)
      Log.create(info: "#{current_user.name} created the #{l(@lunchtable.created_at,format: :short)} table.")
      redirect_to @lunchtable, notice: "Success!!1"
    else
      render :edit
    end
  end

  def show
    @lunchtable = Lunchtable.find(params[:id])
    @lunches = Lunch.where(lunchtable: @lunchtable)
    @lunch = @lunches.new
    render component: 'TableShow', props: { table: @lunchtable, users: @lunchtable.users, lunches: @lunches, current_user: current_user.id }, tag: 'span', class: 'table'

  end

  def destroy
    @lunchtable = Lunchtable.find(params[:id])
    Log.create(info: "#{current_user.name} closed #{l(@lunchtable.created_at,format: :short)} table.")
    Log.create(info: "***************************************************************************************")
    @lunchtable.users.each do |user|
      lunch = user.lunches.find_by(lunchtable: @lunchtable)
      user.update_bal(@lunchtable.price, lunch.paid)
      Log.create(info: "#{user.name}'s balance was updated because of a #{l(@lunchtable.created_at,format: :short)} table closed. (price: #{@lunchtable.price}, paid: #{lunch.paid})")
    end
      Log.create(info: "***************************************************************************************")
    @lunchtable.destroy
    redirect_to lunchtables_path
  end

  def edit
    @lunchtable = Lunchtable.find(params[:id])
  end

  def update
    @lunchtable = Lunchtable.find(params[:id])
    x = lunchtable_params
    prevprice = @lunchtable.price
    x[:total] = (lunchtable_params[:price].to_i * @lunchtable.users.length).to_f
    x[:price] = x[:price].to_i
    if @lunchtable.update(x)
      Log.create(info: "#{current_user.name} updated the price from #{prevprice} to #{x[:price]}")
      redirect_to action: :show, notice: "Success!!1"
    else
      render :edit
    end
  end
  private

  def lunchtable_params
    params.require(:lunchtable).permit(:price)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/lunches_helper.rb
module LunchesHelper
end

app/helpers/lunchtables_helper.rb
module LunchtablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lunchtime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "Logs", logs_index_path %>
  <%= link_to "Tables", lunchtables_path %>
  <% if user_signed_in? %>
  <%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %>
  Current balance: <%= current_user.balance %>
  <%else%>
  <%= link_to "Sign in", new_user_session_path%>
  <%end%>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/logs/destroy.html.erb
<h1>Logs#destroy</h1>
<p>Find me in app/views/logs/destroy.html.erb</p>

app/views/logs/index.html.erb
<h1>Horrible Logs</h1>
<%= link_to "Flush", logs_destroy_path %><br>
<% @logs.each do |log| %>
<%= log.info %> <br>
<%end%>

app/views/lunches/create.html.erb
<h1>Lunches#create</h1>
<p>Find me in app/views/lunches/create.html.erb</p>

app/views/lunches/edit.html.erb
<%= form_for @lunch do |f| %>
      <h3>How Much?:</h3>
       <%= f.text_field :paid, placeholder: "paid" %>
    <%= f.submit  "Pay!"%>
<% end %>

app/views/lunches/index.html.erb
<h1>Lunches#index</h1>
<p>Find me in app/views/lunches/index.html.erb</p>

app/views/lunches/new.html.erb
<h1>Lunches#new</h1>
<p>Find me in app/views/lunches/new.html.erb</p>

app/views/lunches/show.html.erb
<h1>Lunches#show</h1>
<p>Find me in app/views/lunches/show.html.erb</p>

app/views/lunchtables/_form.html.erb
<%= form_for @lunchtable do |f| %>
      <h3>Price?:</h3>
       <%= f.text_field :price, placeholder: "price" %>
    <%= f.submit  %>
<% end %>

app/views/lunchtables/edit.html.erb
<%= render "form" %>

app/views/lunchtables/index.html.erb
<h1>Open Lunch Tables</h1>
<h2><%= link_to "New Table", new_lunchtable_path %></h2>
<% @table.each do |post| %>
<h2><%= link_to l(post.created_at,format: :short), post %></h2>
<h5><%=post.users.length %> People joined this table</h5> <br>
<%end%>

app/views/lunchtables/new.html.erb
<%= render "form" %>

app/views/lunchtables/show.html.erb
<h1><%=l @lunchtable.created_at, format: :short%> Table</h1>

<h2>Price per capita: <%=@lunchtable.price%> <%= link_to "Change", edit_lunchtable_path( @lunchtable ) %>  |  Total Cost: <%=@lunchtable.total %></h2>

<h2>Joined:</h2>
<% @lunches.each do |post| %>
<strong><%= post.user.name %> paid: <%= post.paid %>
  <%if post.user_id == current_user.id %>
    <%= link_to "Pay", edit_lunch_path(post)%>
    <%=link_to "Leave", post, method: :delete, data: { confirm: "Are you sure?" } %>
  <%end%>

  </strong><br>
<%end%>

<%= form_for @lunch do |f| %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= hidden_field_tag(:lunchtable_id, "#{@lunchtable.id}") %>
        <%= f.submit "Join" %>
<% end %>

<%=link_to "Close Table", @lunchtable, method: :delete, data: { confirm: "Are you sure?" } %>